using Nexa.Localization.SourceGenerator.Models;
using System;
using System.Text;
using Nexa.Localization.SourceGenerator.Utilities;

namespace Nexa.Localization.SourceGenerator.CodeGeneration;

internal sealed class CSharpCodeGenerator
{
    public string Generate(LocalizationTree tree)
    {
        if (tree == null)
            throw new ArgumentNullException(nameof(tree));

        var builder = new IndentedStringBuilder();

        WriteHeader(builder);

        WriteRootClass(builder, tree.Root);

        return builder.ToString();
    }

    private static void WriteHeader(IndentedStringBuilder builder)
    {
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Nexa.Localization.Generated;");
        builder.AppendLine();
    }

    private static void WriteRootClass(
        IndentedStringBuilder builder,
        LocalizationNode root)
    {
        builder.AppendLine("public static class NexaKeys");
        builder.AppendLine("{");

        builder.Indent();

        foreach (var child in root.Children.Values)
        {
            WriteNode(builder, child);
            builder.AppendLine();
        }

        builder.Unindent();

        builder.AppendLine("}");
    }

    private static void WriteNode(
        IndentedStringBuilder builder,
        LocalizationNode node)
    {
        // Leaf => const string
        if (node.IsLeaf)
        {
            builder.AppendLine(
                $"public const string {IdentifierSanitizer.Sanitize(node.Name)} = \"{node.FullKey}\";");

            return;
        }

        // Nested class
        builder.AppendLine(
            $"public static class {IdentifierSanitizer.Sanitize(node.Name)}");
        builder.AppendLine("{");

        builder.Indent();

        foreach (var child in node.Children.Values)
        {
            WriteNode(builder, child);
            builder.AppendLine();
        }

        builder.Unindent();

        builder.AppendLine("}");
    }
}