<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.28" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexa.Localization\Nexa.Localization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Components\" />
    <Folder Include="Interop\" />
    <Folder Include="Models\" />
    <Folder Include="wwwroot\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
